# Generated by Django 2.0.4 on 2018-04-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img_lg', models.ImageField(blank=True, null=True, upload_to='media/albums/large')),
                ('img_md', models.ImageField(blank=True, null=True, upload_to='media/albums/medium')),
                ('img_sm', models.ImageField(blank=True, null=True, upload_to='media/albums/small')),
                ('img_xs', models.ImageField(blank=True, null=True, upload_to='media/albums/xs')),
                ('year', models.DateTimeField()),
                ('runtime', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.TextField()),
                ('notes', models.TextField()),
                ('position', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img_lg', models.ImageField(blank=True, null=True, upload_to='media/albums/large')),
                ('img_md', models.ImageField(blank=True, null=True, upload_to='media/albums/medium')),
                ('img_sm', models.ImageField(blank=True, null=True, upload_to='media/albums/small')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('runtime', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('position', models.IntegerField(default=-1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resthampton_app.Album')),
            ],
        ),
        migrations.CreateModel(
            name='SongPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partType', models.CharField(choices=[('Verse', 'Verse'), ('Chorus', 'Chorus'), ('Hook', 'Hook'), ('Bridge', 'Bridge'), ('Intro', 'Intro'), ('Outro', 'Outro'), ('Skit', 'Skit'), ('Pre-Chorus', 'Pre-Chorus'), ('Breakdown', 'Breakdown')], max_length=100)),
                ('runtime', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('position', models.IntegerField(default=-1)),
                ('lyrics', models.TextField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resthampton_app.Song')),
            ],
        ),
        migrations.CreateModel(
            name='SongPartToPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationshipType', models.CharField(choices=[('Writer', 'Writer'), ('Producer', 'Producer')], max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resthampton_app.Person')),
                ('songPart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resthampton_app.SongPart')),
            ],
        ),
        migrations.CreateModel(
            name='SongToPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationshipType', models.CharField(choices=[('Writer', 'Writer'), ('Producer', 'Producer')], max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resthampton_app.Person')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resthampton_app.Song')),
            ],
        ),
        migrations.AddField(
            model_name='bar',
            name='songpart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resthampton_app.SongPart'),
        ),
    ]
